"""initial

Revision ID: 16f4532495ad
Revises: 
Create Date: 2023-12-13 12:43:21.542307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f4532495ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbrev', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=64), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_symbol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=64), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_symbol_ticker'), 'security_symbol', ['ticker'], unique=False)
    op.create_table('security_daily_price',
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('data_vendor_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('open_price', sa.Numeric(), nullable=True),
    sa.Column('high_price', sa.Numeric(), nullable=True),
    sa.Column('low_price', sa.Numeric(), nullable=True),
    sa.Column('close_price', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['data_vendor_id'], ['data_vendor.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security_symbol.id'], ),
    sa.PrimaryKeyConstraint('security_id', 'date')
    )
    op.create_index(op.f('ix_security_daily_price_date'), 'security_daily_price', ['date'], unique=False)
    op.create_index(op.f('ix_security_daily_price_security_id'), 'security_daily_price', ['security_id'], unique=False)
    op.create_table('security_minute_price',
    sa.Column('data_vendor_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('open_price', sa.Numeric(), nullable=True),
    sa.Column('high_price', sa.Numeric(), nullable=True),
    sa.Column('low_price', sa.Numeric(), nullable=True),
    sa.Column('close_price', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['data_vendor_id'], ['data_vendor.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security_symbol.id'], ),
    sa.PrimaryKeyConstraint('security_id', 'date')
    )
    op.create_index(op.f('ix_security_minute_price_date'), 'security_minute_price', ['date'], unique=False)
    op.create_index(op.f('ix_security_minute_price_security_id'), 'security_minute_price', ['security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_minute_price_security_id'), table_name='security_minute_price')
    op.drop_index(op.f('ix_security_minute_price_date'), table_name='security_minute_price')
    op.drop_table('security_minute_price')
    op.drop_index(op.f('ix_security_daily_price_security_id'), table_name='security_daily_price')
    op.drop_index(op.f('ix_security_daily_price_date'), table_name='security_daily_price')
    op.drop_table('security_daily_price')
    op.drop_index(op.f('ix_security_symbol_ticker'), table_name='security_symbol')
    op.drop_table('security_symbol')
    op.drop_table('exchange')
    op.drop_table('data_vendor')
    # ### end Alembic commands ###
