"""adding id columns for price tables

Revision ID: 3c0e045cf9cb
Revises: 50acdfd3805b
Create Date: 2024-01-02 21:37:23.637757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0e045cf9cb'
down_revision: Union[str, None] = '50acdfd3805b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_daily_price', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('security_minute_price', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_minute_price', 'id')
    op.drop_column('security_daily_price', 'id')
    # ### end Alembic commands ###
