"""data model improvments

Revision ID: 5e66ce2dfa17
Revises: 16f4532495ad
Create Date: 2023-12-26 18:22:11.033107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e66ce2dfa17'
down_revision: Union[str, None] = '16f4532495ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange', sa.Column('code', sa.String(), nullable=True))
    op.alter_column('exchange', 'abbrev',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange', 'abbrev',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('exchange', 'code')
    # ### end Alembic commands ###
