version: '3.8'

networks:
  redis_net:
    driver: bridge
  database_net:
    driver: bridge
  minio_net:
    driver: bridge
  airflow_net:
    driver: bridge

volumes:
  database-data:
  airflow-logs:
  airflow-dags:
  airflow-plugins:
  db-data:
